steps:
  # Paso 1: Compilar la imagen inyectando la instalación de certificados CA
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'southamerica-east1-docker.pkg.dev/stepsidev2-499621/stepside-repo/stepside-backend-v2:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:latest'
      - '--env=GOOGLE_RUNTIME_VERSION=21'
      - '--env=MAVEN_OPTS=-Dmaven.test.skip=true'
      # ESTA LÍNEA ES LA SOLUCIÓN: Fuerza a Buildpacks a incluir los certificados de confianza de Linux
      - '--env=BP_ENABLE_RUNTIME_CERT_INJECTION=true'

  # Paso 2: Subir la imagen a la nube
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/stepsidev2-499621/stepside-repo/stepside-backend-v2:$COMMIT_SHA'

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'stepside-backend-v2'
      - '--image=southamerica-east1-docker.pkg.dev/stepsidev2-499621/stepside-repo/stepside-backend-v2:$COMMIT_SHA'
      - '--region=southamerica-east1'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'southamerica-east1-docker.pkg.dev/stepsidev2-499621/stepside-repo/stepside-backend-v2:$COMMIT_SHA'
