steps:
  # Paso 1: Compilar la imagen de Java 21 usando Buildpacks (YA FUNCIONA)
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'southamerica-east1-docker.pkg.dev/stepsidev2-499621/stepside-repo/stepside-backend-v2:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:latest'
      - '--env=GOOGLE_RUNTIME_VERSION=21'
      - '--env=MAVEN_OPTS=-Dmaven.test.skip=true'

  # NUEVO PASO INTERMEDIO: Forzar la subida a Artifact Registry antes del deploy
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/stepsidev2-499621/stepside-repo/stepside-backend-v2:$COMMIT_SHA'

  # Paso 3: Desplegar en Cloud Run (Ahora sí la imagen ya va a estar en la nube)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'stepside-backend-v2'
      - '--image=southamerica-east1-docker.pkg.dev/stepsidev2-499621/stepside-repo/stepside-backend-v2:$COMMIT_SHA'
      - '--region=southamerica-east1'

options:
  logging: CLOUD_LOGGING_ONLY

# Podés dejar esto también como buena práctica para el registro de Cloud Build
images:
  - 'southamerica-east1-docker.pkg.dev/stepsidev2-499621/stepside-repo/stepside-backend-v2:$COMMIT_SHA'
