# ============================================================================
# ORDEN DE IMPORTACIÓN: CARGA EL ARCHIVO DE ENTORNO EN EL CLASSPATH
# ============================================================================
##spring.config.import=file:.env.properties
spring.config.import=optional:file:.env.properties

# CONFIGURACIÓN GENERAL
spring.application.name=StepSide
server.port=${PORT:8080}

### ============================================================================
### ENGRANE CENTRAL DE RED: CONEXIÓN ATLAS CLOUD UNIFICADA
### ============================================================================
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}

# ============================================================================
# CONFIGURACIÓN DEL MOTOR DE NOTIFICACIONES POR EMAIL (SMTP)
# ============================================================================
spring.mail.host=${STEPSIDE_MAIL_HOST}
spring.mail.port=${STEPSIDE_MAIL_PORT}
spring.mail.username=${STEPSIDE_MAIL_USERNAME}
spring.mail.password=${STEPSIDE_MAIL_PASSWORD}

# ESTAS LÍNEAS TIENEN QUE ESTAR DESCOMENTADAS (SIN EL #):
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Tiempos de espera recomendados (descomentados):
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# La línea de confianza con el valor directo:
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ============================================================================
# AUDITORÍA FORENSE: ACTIVACIÓN DE LOGS PARA MONGODB ATLAS NATIVO
# ============================================================================
# Fuerza al driver de Mongo a mostrar IPs, puertos y balanceadores en la consola
#logging.level.org.mongodb.driver.cluster=DEBUG
#logging.level.org.mongodb.driver.connection=DEBUG

# Muestra el mapeo de los documentos BSON y las consultas
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

