# ============================================================================
# ORDEN DE IMPORTACIÓN: CARGA EL ARCHIVO DE ENTORNO EN EL CLASSPATH
# ============================================================================
#spring.config.import=optional:file:.env.properties

# Si no hay variables de entorno externas, activa el archivo de configuración local
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
#####
#########################################################
##Conexión MongoDB
#########################################################
spring.data.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PWD}@${MONGO_URL}/${DATABASE}?connectTimeoutMS=10000&socketTimeoutMS=45000&maxPoolSize=50&minPoolSize=5&maxIdleTimeMS=60000&retryWrites=true&retryReads=true


# CONFIGURACIÓN GENERAL
spring.application.name=StepSide
server.port=${PORT:8080}

# Mapeo elástico de las variables de entorno de StepSide
stepside.jwt.secret=${STEPSIDE_JWT_SECRET}
stepside.jwt.expiration-hours=${STEPSIDE_JWT_EXPIRATION_HOURS}

# Propiedad para el balanceador de Google Cloud que vimos antes
server.forward-headers-strategy=FRAMEWORK

# ============================================================================
# CONFIGURACIÓN DEL MOTOR DE NOTIFICACIONES POR EMAIL (SMTP)
# ============================================================================
spring.mail.host=${STEPSIDE_MAIL_HOST}
spring.mail.port=${STEPSIDE_MAIL_PORT}
spring.mail.username=${STEPSIDE_MAIL_USERNAME}
spring.mail.password=${STEPSIDE_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Tiempos de espera estándar para control de hilos
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Confianza explícita al host original
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3


# ============================================================================
# ACTIVACIÓN DE LOGS PARA MONGODB
# ============================================================================
# Fuerza al driver de Mongo a mostrar IPs, puertos y balanceadores en la consola
#logging.level.org.mongodb.driver.cluster=DEBUG
#logging.level.org.mongodb.driver.connection=DEBUG
#logging.level.org.mongodb.driver.cluster=DEBUG
#logging.level.org.mongodb.driver.connection=DEBUG


# ============================================================================
# Muestra el mapeo de los documentos BSON y las consultas
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

